travis:
  secure:
    BINSTAR_TOKEN: Bu7x58cmaupM/PSp+tIz3yXpERFZv21PmJ2aNE9IxBgLZGe/mkg4wrFcGBq+KREgB9TvdzUGSO9fIK3DL05Z+SEHEbavEUjiYaV3fLpuwrE0CW8pNWMWIkPg4lmbDlgvt7MCJUgutQW6IETPgnz6VTksyG0Udd3asXk8gW+biiMZ4dDblrYy2q30F8vC2tiHHkvyR6vSGgroZzRrtz5R5nrdlhZa2A5+8aip3U5uoBMdxTUn2X9mBvwgzVYb49ttzmjW8Zbi5Rti31OoOTwWqQqj4jNZeRhUSZtAOwm2gLQWtLbn5vfDD4r9dppZxVjao+RcczUfbS8Ma8T6rAOiTGPJELbaaDnM7MAKTukLBPUc7YULXqHurGndrtcz5PsaGKRfg/Rc/Fd5/cuP5zmNvNczcP0B3myJmqE45FoM9TQnTskpXqJhTM6wMwR3UsRcZoVvpkaTaj/5RBwaiZ0s9xhOFICto4ojqObipBkT+q0K0g3tO16rmFie4zkONtNB5nGaTatnaSnti2HsiHAlsqp+sO0z0k8htOuf4GeBAliQKTU1QQuVsHN59qaiRiehSgPAGgNRvOvyLdCCwrRV843hN+KEYcstoQpBbMDkCrsiyxDqkwrYBrYQODKq+KI1CR753TtGHH/oveP8y+URLTObz0q1Zfe7Xagp5J1fdUg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
