travis:
  secure:
    BINSTAR_TOKEN: T/5sw9/xzpK7Z5Ko4oIoPdsQNjWXr89PvsVkSkKqtfJCIPvkAkZcZANtgyB5QbfYQDHhLrXNUxWxo4HF0Drk5+2YFlU/eZZiVtvPr0vt3pF/7ncNjtVewsdvOVcxFoSDrk84lUW8SXJzGkq0tJ+DLtJEKnazjNXzpGj7FhU17j+mNFjxmV61+SADIspXVojDAePELPjk0fn2b0wBLDpTL0FmTeNE91241//6hEC5ljLF4RV90k4YtylCi7C+P/vAussEwxnjOD9j1jRM5Pt+y1ykT/fu7s+A0aV6K5KHuJOOp0yXlk9+5HUwtex+5lyrw9VLoQBnYyM4u4PPjNlth8F+08OlCnPh6oho3ne4b3txfT9gyApmcEF0zT/1QKzkPYfiaEw3D7uMNdxIA/888+9wdzMnbwQY/3hs2qrT23d3tn716ci3kFua6GWD1NCA7dkbbkZ9+XI/LZPxcon8vny0oXPcBC/avpNf4+nxp6moITciYtLihs7ByQFWPSYzTqsQnokLVcNOb+pQ1gWf/3DyRWJ0e6gUbSPHtzKI2Ls7iZ3edyWuZ9HreaD6OG7S9nVsinhbT+c0y9we6Wv6kpiMtm9bX4cqbrqtL8nQgQ82l8KnftpvPYni65ojLK5qZ1Bex5RGRMP4Co1ZVwpj8YKRz5v2PztjvCcEnW+DrQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
